import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { toast } from '../Enhancements'
import { specs, type Field, type Result, type Values } from './specs'
import './extra-tools.css'

export const isExtraTool = (id: string) => Object.prototype.hasOwnProperty.call(specs, id)

const initial = (fields: Field[]): Values =>
  Object.fromEntries(fields.map((f) => [f.key, f.def ?? (f.type === 'select' ? String(Array.isArray(f.options?.[0]) ? f.options[0][0] : f.options?.[0] ?? '') : '')]))

const copy = (value: string, label = 'Copied to clipboard') => { navigator.clipboard?.writeText(value); toast(label) }

const save = (blob: Blob, name: string) => {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = name; a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

const savePng = (svg: string, name: string) => {
  const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' }))
  const img = new Image()
  img.onload = () => {
    const c = document.createElement('canvas')
    c.width = c.height = 1024
    const ctx = c.getContext('2d')
    if (ctx) { ctx.imageSmoothingEnabled = false; ctx.drawImage(img, 0, 0, 1024, 1024) }
    URL.revokeObjectURL(url)
    c.toBlob((b) => { if (b) save(b, name) })
  }
  img.src = url
}

// Turns "background:linear-gradient(...)" / "box-shadow: ..." (generated by our own specs) into a style object.
const cssToStyle = (css: string): CSSProperties => {
  const i = css.indexOf(':')
  if (i < 0) return {}
  const prop = css.slice(0, i).trim().replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
  return { [prop]: css.slice(i + 1).trim() } as CSSProperties
}

function Input({ f, value, set, setFiles }: { f: Field; value: string; set: (v: string) => void; setFiles: (files: File[]) => void }) {
  const id = `xt-${f.key}`
  if (f.type === 'textarea') return <textarea id={id} className="editor xt-textarea" value={value} placeholder={f.placeholder} spellCheck={false} onChange={(e) => set(e.target.value)} />
  if (f.type === 'select') return <select id={id} value={value} onChange={(e) => set(e.target.value)}>{(f.options ?? []).map((o) => { const [v, l] = Array.isArray(o) ? o : [o, o]; return <option key={v} value={v}>{l}</option> })}</select>
  if (f.type === 'file') return <input id={id} type="file" accept={f.accept} onChange={(e) => setFiles(Array.from(e.target.files ?? []))} />
  if (f.type === 'color') return <input id={id} type="color" value={/^#[0-9a-f]{6}$/i.test(value) ? value : '#000000'} onChange={(e) => set(e.target.value)} />
  if (f.type === 'range') return <span className="xt-range"><input id={id} type="range" min={f.min} max={f.max} step={f.step} value={value} onChange={(e) => set(e.target.value)} /><output>{value}</output></span>
  const type = f.type === 'number' ? 'number' : f.type === 'password' ? 'password' : f.type === 'datetime' ? 'datetime-local' : 'text'
  return <input id={id} type={type} min={f.min} max={f.max} step={f.step} value={value} placeholder={f.placeholder} autoComplete="off" onChange={(e) => set(e.target.value)} />
}

function Output({ result, id }: { result: Exclude<Result, string>; id: string }) {
  const { rows, text, note, previewCss, html, svg } = result
  return <div className="result xt-result" aria-live="polite">
    <div className="result-head"><span>Result</span>
      {(text || svg) && <span className="xt-head-actions">
        {text && <button type="button" onClick={() => copy(text)}>Copy</button>}
        {svg && <><button type="button" onClick={() => save(new Blob([svg], { type: 'image/svg+xml' }), `${id}.svg`)}>Download SVG</button><button type="button" onClick={() => savePng(svg, `${id}.png`)}>Download PNG</button></>}
      </span>}
    </div>
    {previewCss && <div className="xt-preview" style={cssToStyle(previewCss)} aria-hidden="true" />}
    {svg && <div className="xt-qr" dangerouslySetInnerHTML={{ __html: svg }} role="img" aria-label="Generated QR code" />}
    {html && <div className="xt-html" dangerouslySetInnerHTML={{ __html: html }} />}
    {text && <pre>{text}</pre>}
    {rows && <div className="xt-rows" role="table">{rows.map(([label, value, swatch], i) => <div className="xt-row" role="row" key={`${label}-${i}`}>
      <span className="xt-label" role="rowheader">{swatch && <i className="xt-swatch" style={{ background: swatch }} />}{label}</span>
      <span className="xt-value" role="cell">{value}</span>
      <button type="button" className="xt-copy" aria-label={`Copy ${label}`} onClick={() => copy(value)}>Copy</button>
    </div>)}</div>}
    {note && <p className="xt-note">{note}</p>}
  </div>
}

export default function ExtraToolPanel({ id }: { id: string }) {
  const spec = specs[id]
  const [values, setValues] = useState<Values>(() => initial(spec.fields))
  const [files, setFiles] = useState<File[]>([])
  const [result, setResult] = useState<Result>('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const run = useRef(0)

  const execute = async () => {
    const ticket = ++run.current
    setBusy(true)
    try {
      const r = await spec.run(values, files)
      if (ticket !== run.current) return
      setResult(r); setError('')
    } catch (e) {
      if (ticket !== run.current) return
      setResult(''); setError(e instanceof Error ? e.message : 'Something went wrong.')
    } finally {
      if (ticket === run.current) setBusy(false)
    }
  }

  useEffect(() => {
    if (spec.manual) return
    const t = setTimeout(execute, 120)
    return () => clearTimeout(t)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [values, files])

  const set = (k: string) => (v: string) => setValues((x) => ({ ...x, [k]: v }))
  const reset = () => { setValues(initial(spec.fields)); setFiles([]); setResult(''); setError('') }
  const hasResult = typeof result !== 'string'

  return <div className="xt-panel" onKeyDown={(e) => { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); execute() } }}>
    <div className="controls xt-controls">
      {spec.fields.map((f) => <label key={f.key} htmlFor={`xt-${f.key}`} className={f.type === 'textarea' ? 'xt-wide' : undefined}>{f.label}<Input f={f} value={values[f.key] ?? ''} set={set(f.key)} setFiles={setFiles} /></label>)}
    </div>
    <div className="actions">
      {spec.manual && <button type="button" className="primary" onClick={execute} disabled={busy}>{spec.runLabel ?? 'Run tool'}</button>}
      <button type="button" className="secondary" onClick={reset}>Reset</button>
    </div>
    {error && <div className="error" role="alert">{error}</div>}
    {!error && !hasResult && <div className="result-empty" aria-hidden="true"><strong>Your result appears here</strong><span>{spec.empty ?? (spec.manual ? 'Choose your options, then press the button.' : 'Fill in the fields above.')}</span></div>}
    {!error && hasResult && <Output result={result} id={id} />}
  </div>
}
