// Unique intro + FAQ copy for Security tools.
import type {ToolCopy} from './types'
export const securityCopy:Record<string,ToolCopy>={
 'password-generator':{faq:[["How long should a password be?","Use at least 14–16 characters. Length matters more than complexity."],["Is the generated password stored?","No. It is created in your browser and never sent anywhere."],["Should I reuse passwords?","Never. Use a unique password per account and a password manager."]]},
 'sha-256':{faq:[["What is SHA-256?","A cryptographic hash function that turns any input into a fixed 256-bit (64 hex character) fingerprint."],["Can SHA-256 be reversed?","No. Hashing is one-way, although weak inputs can be guessed."],["Is SHA-256 good for passwords?","Not on its own. Use a slow, salted algorithm such as bcrypt or Argon2."]]},
 'sha-512':{faq:[["How long is a SHA-512 hash?","128 hexadecimal characters (512 bits)."],["Is SHA-512 more secure than SHA-256?","Both are considered secure; SHA-512 has a longer output and can be faster on 64-bit systems."],["Does the same input always give the same hash?","Yes, hashing is deterministic."]]},
 'md5':{faq:[["Is MD5 secure?","No. MD5 is broken for security use, but is still fine for non-security checksums."],["What is MD5 used for?","Quick file or data fingerprints and legacy systems."],["Can MD5 be decrypted?","It is not encryption, but weak inputs can be found with lookup tables."]]},
 'sha-1':{faq:[["Is SHA-1 still safe?","SHA-1 is deprecated for security because collisions can be created. Use SHA-256 or stronger."],["Where is SHA-1 still used?","Legacy systems and Git object IDs."],["How long is SHA-1 output?","40 hexadecimal characters (160 bits)."]]},
 'html-encoder':{faq:[["Why encode HTML?","Converting < > & and quotes to entities prevents text from being interpreted as markup."],["Does encoding prevent XSS?","It is a key defence when output is placed in HTML, together with context-aware escaping in your framework."],["Which characters are encoded?","The characters & < > \" and '."]]},
 'html-decoder':{faq:[["What does the HTML decoder do?","It turns entities such as &amp; and &lt; back into the characters they represent."],["Are numeric entities supported?","Yes, both named and numeric entities are decoded."],["Is the decoded output safe to insert in a page?","Decoded text can contain markup, so escape it again before rendering untrusted content."]]},
 'random-number-generator':{faq:[["Is the number truly random?","It uses the browser’s secure random generator, which is suitable for giveaways and games."],["Can I generate several numbers?","Yes, choose how many numbers you need and whether duplicates are allowed."],["Are the min and max inclusive?","Yes, both ends of the range can be generated."]]},
 'password-strength-checker':{intro:"Check how strong a password is and get suggestions to improve it. Analysis runs in your browser, so the password is never sent anywhere.",faq:[["What makes a password strong?","Length, unpredictability and not reusing it elsewhere."],["Is it safe to type my real password?","The check runs locally, but use a similar test password if you prefer."],["Does a high score guarantee safety?","No. A strong password can still be exposed in a breach, so use unique passwords and two-factor authentication."]]},
}
